<nav class="navbar navbar-fixed-top " style="border-bottom-color: #6699ff;">
   <div class="container" align="center">
    <h4>Detalle de calendario</h4>
  </div> 
</nav>

<nav class="navbar navbar-fixed-top ">
    <a class="btn bnt-default btn-lg" id="backtocal">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </a>
</nav>

<br><br><br>
<iframe src="<?php echo $this->url; ?>" style="border: 0" width="100%" height="350" frameborder="0" scrolling="no"></iframe>

<script>
$(document).ready(function() {
  $.getScript("lib/vcl/nav.js",function() {
    $("#backtocal").click(function() { show("calendar","index","#view",""); });
  });
});
</script>