<h2><i class="fas fa-calendar-day fa-sm"></i> Calendarios</h2>
            
            <!-- Listado de coros -->
            
            <table class="table table-borderless table-sm">
              <tbody>
                <tr>
                  <td>
                    <iframe src="https://calendar.google.com/calendar/embed?src=8vfkt0dsl4kr99o5gl3ls4o8h4%40group.calendar.google.com&amp;ctz=America%2FGuatemala&amp;showPrint=0&amp;mode=AGENDA&amp;showTitle=1&amp;showTz=0&amp;showTabs=0&amp;showNav=0&amp;showDate=0&amp;showCalendars=0&amp;hl=es" style="border: 0" width="100%" height="100" frameborder="0" scrolling="yes"></iframe>
                  </td>
                  <td style="vertical-align: bottom;">
                    <a id="coro1">
                        <img src="img/ver.png" width="50"/>
                    </a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <iframe src="https://calendar.google.com/calendar/embed?src=uouskn5366sr94s0726kp03l1k%40group.calendar.google.com&amp;ctz=America%2FGuatemala&amp;showPrint=0&amp;mode=AGENDA&amp;showTitle=1&amp;showTz=0&amp;showTabs=0&amp;showNav=0&amp;showDate=0&amp;showCalendars=0&amp;hl=es" style="border: 0" width="100%" height="100" frameborder="0" scrolling="yes"></iframe>
                  </td>
                  <td style="vertical-align: bottom;">
                    <a id="coro2">
                        <img src="img/ver.png" width="50"/>
                    </a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <iframe src="https://calendar.google.com/calendar/embed?src=e7evnmapvqde269t19pujbu70k%40group.calendar.google.com&amp;ctz=America%2FGuatemala&amp;showPrint=0&amp;mode=AGENDA&amp;showTitle=1&amp;showTz=0&amp;showTabs=0&amp;showNav=0&amp;showDate=0&amp;showCalendars=0&amp;hl=es" style="border: 0" width="100%" height="100" frameborder="0" scrolling="yes"></iframe>
                  </td>
                  <td style="vertical-align: bottom;">
                    <a id="coro3">
                        <img src="img/ver.png" width="50"/>
                    </a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <iframe src="https://calendar.google.com/calendar/embed?src=icb911hs2fk4g8g1ei9fsah6ng%40group.calendar.google.com&amp;ctz=America%2FGuatemala&amp;showPrint=0&amp;mode=AGENDA&amp;showTitle=1&amp;showTz=0&amp;showTabs=0&amp;showNav=0&amp;showDate=0&amp;showCalendars=0&amp;hl=es" style="border: 0" width="100%" height="100" frameborder="0" scrolling="yes"></iframe>
                  </td>
                  <td style="vertical-align: bottom;">
                    <a id="coro4">
                        <img src="img/ver.png" width="50"/>
                    </a>
                  </td>
                </tr>
              </tbody>
            </table>

<script>
$(document).ready(function() {
  $.getScript("lib/vcl/nav.js",function() {
    $("#coro1").click(function() { show("calendar","detail","#view","cal=coro1"); });
    $("#coro2").click(function() { show("calendar","detail","#view","cal=coro2"); });
    $("#coro3").click(function() { show("calendar","detail","#view","cal=coro3"); });
    $("#coro4").click(function() { show("calendar","detail","#view","cal=coro4"); });
  });
});
</script>