<div class="page-header">
  <h2><?php echo $this->title; ?>
    <small>
      <?php echo $this->object->Id == '' ? 'Nuevo' : 'Editar'; ?>
    </small>
    <a id="cancelar" class="btn btn-danger btn-sm">
      <span class="glyphicon glyphicon-remove"></span> Cancelar
    </a>
  </h2>
</div>
<div class="row">
  <div class="col-md-4">
    <form id="form" action="javascript:void(0);"
      enctype="multipart/form-data">
      <input name = "Id" type="hidden" class="form-control"
        value="<?php
            echo $this->object->Id == '' ? '0' : $this->object->Id;
          ?>"/>

<?php
  foreach($this->object as $key => $value)	{
    if ($key!='Id') {
      $type = 'text';

      if ($this->is_Date($value)) {
        $type = 'date';
        $value = date('Y-m-d',strtotime($value));
      }
?>
      <div class="form-group">
        <label for="<?php echo $key; ?>"><?php echo $key; ?>:</label>
        <input class="form-control" name = "<?php echo $key; ?>"
          type="<?php echo $type; ?>" value="<?php echo $value; ?>"/>
      </div>
<?php
    }
  }
?>
      <button type="submit" class="btn btn-success">
        <span class="glyphicon glyphicon-floppy-disk"></span> Guardar
      </button>
    </form>
  </div>
</div>

<script>
$(document).ready(function(){
  $.getScript("lib/vcl/nav.js",function() {
    $("#form").submit(function(event) {
      show("<?php echo $this->controller; ?>","edit","#view",$(this).serialize());
    });
    $("#cancelar").click(function() {
      show("<?php echo $this->controller; ?>","index","#view","");
    });
  });
});
</script>
